VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false

  config.vm.define "mezzanine" do |mezzanine|
    mezzanine.vm.box = "ubuntu/trusty64"
    mezzanine.vm.network "forwarded_port", guest: 80, host: 8080
    mezzanine.vm.network "forwarded_port", guest: 443, host: 8443
  end
end
